### ISSUE TITLE
Screen turning on randomly

### ISSUE THREAD

**Issue by krustbr** [mmontuori/atrix-mrom#10]
today my atrix starts turning on the screen(like ive had pushed the button) automatically and randomly.
I just turn off the screen and he keeps turning on.
Here the log: https://rapidshare.com/files/2373320583/errorscreen2.txt

Version: 09-15

**Comment by mmontuori** [comment]
I looked at the logs, it appears that you have hundreds of errors related to LBAdController... I would remove this application and see if the screen problem goes away... this will also clean up logs for me to better look at them...

**Comment by krustbr** [comment]
This error stops occurring, apparently without any action performed by me.
The only thing ive had done yesterday, different from usual, was that i play some mp3 and change things up the equalizer. Didnt know if its help or r related to something, just saying, Thanks

And i tried yesterday, during this error, to reboot the phone several times, didnt fix, but, he "fix" by itself. Weird

**Comment by mmontuori** [comment]
this is weird, I am glad the error went away though...
