### ISSUE TITLE
Possible security vulnerability

### ISSUE THREAD

**Issue by ravilov** [mmontuori/atrix-mrom#14]
XDA thread: http://forum.xda-developers.com/showthread.php?t=1907142
Source: http://www.pcworld.idg.com.au/article/437505/how_check_your_android_phone_vulnerable_ussd_security_flaw/?fp=4

According to this, many ROMs/phones out there are affected, MROM included. This could enable a malicious web page to perform a factory reset without any confirmation or warning.

Maybe you could look into this, see if it's easy to patch? Then maybe even send the patch upstream to CM Team or Moto Tegra Team.

**Comment by mmontuori** [comment]
Looking into it...

**Comment by ravilov** [comment]
It appears there might be no need to fix this yourself, just wait for it to be integrated into the next stable release.

 https://plus.google.com/u/0/+CyanogenMod/posts/DERxg7p3aLm

**Comment by mmontuori** [comment]
Great, we should see the code appear in the repo soon...

**Comment by mmontuori** [comment]
I don't think the latest build curved the problem. Can you test please?

**Comment by ravilov** [comment]
Seems it did actually.

Here's the test page: http://www.isk.kth.se/~rbbo/testussd.html
Used to when I went to that page using my phone, it redirected to the dialer and showed my IMEI.
On the latest build it also redirects to the dialer, but it just shows `*#06#` there as if I typed it on the keypad.

**Comment by mmontuori** [comment]
great news, i tested it also... closing the bug then... thanks
