### ISSUE TITLE
Possible issue with MROM check version app?

### ISSUE THREAD

**Issue by ravilov** [mmontuori/atrix-mrom#15]
This is how it went for me. I'm still on 9/15, I didn't get the notification (I know, those only happen automatically on boot). I ran the MROM check version app and clicked to check, still nothing. I tried this several times, nothing. Then I rebooted and I got the notification immediately. I cleared that and went to check manually through the app, and now the app showed the notification too.

**Comment by mmontuori** [comment]
Sorry that was my site, now it sound work every time...

**Comment by ravilov** [comment]
Ah I see. OK, closing this issue then.
