### ISSUE TITLE
After phone call, screen does not wake up / turn on

### ISSUE THREAD

**Issue by swxbw** [mmontuori/atrix-mrom#18]
Randomly (no pattern found yet); my phone does not wake up after the screen turned off...
I cannot send you the CatLog file, since I can only see what happened after the reboot (unmounting and mounting my battery is the only thing I can do really...)

Was this reported before? I just used your MROM latest version (10-08); I did not install a special kernel.

Thanks in advance!

**Comment by mmontuori** [comment]
Phone should still be alive, lanky experience with the screen of death is done application is preventing the phone from waking up like juice defender... if you don't have the app installed try to correct adb logcat connecting the computer via usb and send it to me..

**Comment by swxbw** [comment]
Hello Michael,
First of all, congratulations with this ROM, it is my daily ROM and I like the speed and battery life of it!
I have found out that this issue (screen not turning on) only happens when in have an external SD inserted; I tried many other SD cards, but all give the same problem at random moments.I would like to keep Juice Defender installed, since it is really a battery saver. Or what would you suggest?
Thanks for informing,Kind regards,

DieterDate: Mon, 22 Oct 2012 20:43:59 -0700

**Comment by mmontuori** [comment]
Still waiting for the logcat file?

**Comment by swxbw** [comment]
Dear Michael,
you can close this topic. After installing a new kernel (I have tried your last hv & sv  version), the problem never reoccured; even with an SD card mounted.
Thanks for the support!Keep up the great work.
Date: Sat, 27 Oct 2012 18:03:59 -0700

**Comment by mmontuori** [comment]
Closing issue
