### ISSUE TITLE
camera seems to popple like water surface

### ISSUE THREAD

**Issue by jlm346383101** [mmontuori/atrix-mrom#20]
camera seems to popple like water surface！！！

**Comment by mmontuori** [comment]
The stock camera  or miui camera? Then what is the condition that makes this happen?

**Comment by jlm346383101** [comment]
sorry for that! I almost never use the camera,but I use it in the night , so it happens.Now i get you email, I try it again and it work well.I think it normal in the night!

thanks for your reply!

------------------ 原始邮件 ------------------
发件人: "Michael Montuori"notifications@github.com;
发送时间: 2012年10月28日(星期天) 上午9:02
收件人: "mmontuori/atrix-mrom"atrix-mrom@noreply.github.com; 
抄送: "jlm346383101"346383101@qq.com; 
主题: Re: [atrix-mrom] camera seems to popple like water surface (#20)

The stock camera  or miui camera? Then what is the condition that makes this happen?

```
           —
           Reply to this email directly or view it on GitHub.
```

**Comment by jlm346383101** [comment]
Your rom is beautiful! But I think many poeple like me don't like the black background like in-calling,in-system-settings and so on! Just some personal advice£¡
Thanks£¡
