### ISSUE TITLE
Smoothness via build.prop tweak: debug.composition.type=gpu

### ISSUE THREAD

**Issue by ghost** [mmontuori/atrix-mrom#6]
The problem jjwatmyself reported was that holo launcher isn't smooth enough.

I found a solution on the net: debug.sf.hw=1 and additionally for even more smoothness debug.composition.type=gpu.
The first thing is already included in MROM, but the second isn't. So I thought I'll try these line. The result was how I expected: A litte more overall smoothness. Maybe it's just a placebo effect.... one should investigate into this to be sure. (Tried it on CM7, not MROM)
Also the guy on the net said that adding debug.composition.type=cpu after the line with gpu results in even more smoothness, because it uses both, gpu and cpu to render the UI.
I don't know if it actually worked, just a placebo effect smoothing things up I guess. I think the last line overrides the other line, doesn't it?

mmontuori take look at it. You will do your best of it.

EDIT: How do I add the enhancements label?

**Comment by mmontuori** [comment]
Testing the change now for stability, if all OK will include in next build...

**Comment by mmontuori** [comment]
This is considered as an enhancement, changed label to reflect...

**Comment by mmontuori** [comment]
Tested the change, for me did not produce any noticeable improvements, however, no side effects were noted and the setting will be applied for future builds.
